export { default as Dialpad } from './Dialpad';
export { default as Login } from './Login';
export { default as VideoCall } from './VideoCall'; 
export { default as ReceivingCall } from './ReceivingCall'; 
export { default as Register } from './Register'; 
export { default as EndCall } from './EndCall';
export { default as Help } from './Help';
export { default as ChooseConversation } from './ChooseConversation'; 
export { default as HelpDesk} from './HelpDesk';
export { default as Emergency } from './Emergency';
export { default as PublicService} from './PublicService/PublicService';
export { default as PublicServiceEmergency} from './PublicService/PublicServiceEmergency';
export { default as TestView} from './TestView';